all:
	gcc -c shm.c -o shm.o -Wall
	gcc shm.o -o shm
	gcc -c letras.c -o letras.o -Wall
	gcc letras.o -o let
	gcc -c palabras.c -o palabras.o -Wall
	gcc palabras.o -o pal
	rm *.o
clean:
	rm pal let shm
edit:
	nano Makefile

